# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Robert\Repos\OurRecipes\source\display.ui'
#
# Created: Mon Apr 23 22:59:56 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1097, 649)
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.table_Recipes = QtGui.QTableWidget(self.tab_2)
        self.table_Recipes.setGeometry(QtCore.QRect(340, 40, 721, 531))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Recipes.setFont(font)
        self.table_Recipes.setObjectName("table_Recipes")
        self.table_Recipes.setColumnCount(7)
        self.table_Recipes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_Recipes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_Recipes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_Recipes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_Recipes.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_Recipes.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_Recipes.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_Recipes.setHorizontalHeaderItem(6, item)
        self.table_Recipes.horizontalHeader().setDefaultSectionSize(150)
        self.table_Recipes.verticalHeader().setDefaultSectionSize(25)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(50, 20, 46, 13))
        self.label.setObjectName("label")
        self.combo_Chef = QtGui.QComboBox(self.tab_2)
        self.combo_Chef.setGeometry(QtCore.QRect(90, 20, 161, 22))
        self.combo_Chef.setObjectName("combo_Chef")
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 51, 16))
        self.label_2.setObjectName("label_2")
        self.combo_Appliance = QtGui.QComboBox(self.tab_2)
        self.combo_Appliance.setGeometry(QtCore.QRect(90, 50, 161, 22))
        self.combo_Appliance.setObjectName("combo_Appliance")
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(120, 90, 81, 16))
        self.label_3.setObjectName("label_3")
        self.spin_PrepLow = QtGui.QSpinBox(self.tab_2)
        self.spin_PrepLow.setGeometry(QtCore.QRect(30, 90, 71, 22))
        self.spin_PrepLow.setMaximum(9999)
        self.spin_PrepLow.setObjectName("spin_PrepLow")
        self.spin_PrepHigh = QtGui.QSpinBox(self.tab_2)
        self.spin_PrepHigh.setGeometry(QtCore.QRect(210, 90, 71, 22))
        self.spin_PrepHigh.setMaximum(9999)
        self.spin_PrepHigh.setProperty("value", 9999)
        self.spin_PrepHigh.setObjectName("spin_PrepHigh")
        self.spin_CookHigh = QtGui.QSpinBox(self.tab_2)
        self.spin_CookHigh.setGeometry(QtCore.QRect(210, 130, 71, 22))
        self.spin_CookHigh.setMaximum(9999)
        self.spin_CookHigh.setProperty("value", 9999)
        self.spin_CookHigh.setObjectName("spin_CookHigh")
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(120, 130, 81, 16))
        self.label_4.setObjectName("label_4")
        self.spin_CookLow = QtGui.QSpinBox(self.tab_2)
        self.spin_CookLow.setGeometry(QtCore.QRect(30, 130, 71, 22))
        self.spin_CookLow.setMaximum(9999)
        self.spin_CookLow.setObjectName("spin_CookLow")
        self.table_IngredientsFilter = QtGui.QTableWidget(self.tab_2)
        self.table_IngredientsFilter.setGeometry(QtCore.QRect(20, 230, 291, 341))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_IngredientsFilter.setFont(font)
        self.table_IngredientsFilter.setObjectName("table_IngredientsFilter")
        self.table_IngredientsFilter.setColumnCount(2)
        self.table_IngredientsFilter.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_IngredientsFilter.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_IngredientsFilter.setHorizontalHeaderItem(1, item)
        self.table_IngredientsFilter.horizontalHeader().setDefaultSectionSize(250)
        self.table_IngredientsFilter.horizontalHeader().setMinimumSectionSize(5)
        self.table_IngredientsFilter.horizontalHeader().setStretchLastSection(True)
        self.table_IngredientsFilter.verticalHeader().setDefaultSectionSize(25)
        self.table_IngredientsFilter.verticalHeader().setMinimumSectionSize(5)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(690, 20, 46, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(130, 210, 61, 16))
        self.label_6.setObjectName("label_6")
        self.button_Search = QtGui.QPushButton(self.tab_2)
        self.button_Search.setGeometry(QtCore.QRect(240, 580, 71, 23))
        self.button_Search.setObjectName("button_Search")
        self.button_ViewIngredients = QtGui.QPushButton(self.tab_2)
        self.button_ViewIngredients.setGeometry(QtCore.QRect(884, 580, 101, 23))
        self.button_ViewIngredients.setObjectName("button_ViewIngredients")
        self.button_ViewRecipes = QtGui.QPushButton(self.tab_2)
        self.button_ViewRecipes.setGeometry(QtCore.QRect(990, 580, 75, 23))
        self.button_ViewRecipes.setObjectName("button_ViewRecipes")
        self.button_EditRecipe = QtGui.QPushButton(self.tab_2)
        self.button_EditRecipe.setGeometry(QtCore.QRect(450, 580, 101, 23))
        self.button_EditRecipe.setObjectName("button_EditRecipe")
        self.button_DeleteRecipe = QtGui.QPushButton(self.tab_2)
        self.button_DeleteRecipe.setGeometry(QtCore.QRect(340, 580, 101, 23))
        self.button_DeleteRecipe.setObjectName("button_DeleteRecipe")
        self.spin_ServeLow = QtGui.QSpinBox(self.tab_2)
        self.spin_ServeLow.setGeometry(QtCore.QRect(30, 170, 71, 22))
        self.spin_ServeLow.setMaximum(9999)
        self.spin_ServeLow.setObjectName("spin_ServeLow")
        self.spin_ServeHigh = QtGui.QSpinBox(self.tab_2)
        self.spin_ServeHigh.setGeometry(QtCore.QRect(210, 170, 71, 22))
        self.spin_ServeHigh.setMaximum(9999)
        self.spin_ServeHigh.setProperty("value", 9999)
        self.spin_ServeHigh.setObjectName("spin_ServeHigh")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(120, 170, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_deleteOne = QtGui.QLabel(self.tab_2)
        self.label_deleteOne.setGeometry(QtCore.QRect(560, 580, 281, 20))
        self.label_deleteOne.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_deleteOne.setText("")
        self.label_deleteOne.setObjectName("label_deleteOne")
        TabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.text_output = QtGui.QTextBrowser(self.tab_3)
        self.text_output.setGeometry(QtCore.QRect(380, 40, 691, 561))
        font = QtGui.QFont()
        font.setFamily("Calisto MT")
        font.setPointSize(12)
        self.text_output.setFont(font)
        self.text_output.setObjectName("text_output")
        self.list_Viewing = QtGui.QListWidget(self.tab_3)
        self.list_Viewing.setGeometry(QtCore.QRect(30, 40, 331, 261))
        self.list_Viewing.setObjectName("list_Viewing")
        self.label_viewing = QtGui.QLabel(self.tab_3)
        self.label_viewing.setGeometry(QtCore.QRect(30, 20, 46, 13))
        self.label_viewing.setObjectName("label_viewing")
        self.label_Output = QtGui.QLabel(self.tab_3)
        self.label_Output.setGeometry(QtCore.QRect(380, 20, 51, 16))
        self.label_Output.setObjectName("label_Output")
        self.label_viewing_2 = QtGui.QLabel(self.tab_3)
        self.label_viewing_2.setGeometry(QtCore.QRect(30, 320, 131, 16))
        self.label_viewing_2.setObjectName("label_viewing_2")
        self.button_addIngredientView = QtGui.QPushButton(self.tab_3)
        self.button_addIngredientView.setGeometry(QtCore.QRect(120, 420, 91, 23))
        self.button_addIngredientView.setObjectName("button_addIngredientView")
        self.combo_IngredientView = QtGui.QComboBox(self.tab_3)
        self.combo_IngredientView.setGeometry(QtCore.QRect(30, 380, 231, 22))
        self.combo_IngredientView.setObjectName("combo_IngredientView")
        self.double_AmountIngredientView = QtGui.QDoubleSpinBox(self.tab_3)
        self.double_AmountIngredientView.setGeometry(QtCore.QRect(30, 420, 81, 22))
        self.double_AmountIngredientView.setMaximum(9999.99)
        self.double_AmountIngredientView.setSingleStep(0.5)
        self.double_AmountIngredientView.setObjectName("double_AmountIngredientView")
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(30, 350, 91, 20))
        self.label_27.setObjectName("label_27")
        self.label_measureUnitView = QtGui.QLabel(self.tab_3)
        self.label_measureUnitView.setGeometry(QtCore.QRect(280, 380, 51, 20))
        self.label_measureUnitView.setObjectName("label_measureUnitView")
        self.line_noteView = QtGui.QLineEdit(self.tab_3)
        self.line_noteView.setGeometry(QtCore.QRect(100, 350, 261, 20))
        self.line_noteView.setObjectName("line_noteView")
        TabWidget.addTab(self.tab_3, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.combo_ApplianceNewRecipe = QtGui.QComboBox(self.tab)
        self.combo_ApplianceNewRecipe.setGeometry(QtCore.QRect(80, 440, 141, 22))
        self.combo_ApplianceNewRecipe.setObjectName("combo_ApplianceNewRecipe")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 410, 46, 13))
        self.label_8.setObjectName("label_8")
        self.spin_CookNewRecipe = QtGui.QSpinBox(self.tab)
        self.spin_CookNewRecipe.setGeometry(QtCore.QRect(80, 520, 71, 22))
        self.spin_CookNewRecipe.setMaximum(9999)
        self.spin_CookNewRecipe.setObjectName("spin_CookNewRecipe")
        self.combo_ChefNewRecipe = QtGui.QComboBox(self.tab)
        self.combo_ChefNewRecipe.setGeometry(QtCore.QRect(80, 410, 141, 22))
        self.combo_ChefNewRecipe.setObjectName("combo_ChefNewRecipe")
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 520, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 450, 51, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 480, 61, 16))
        self.label_11.setObjectName("label_11")
        self.spin_PrepNewRecipe = QtGui.QSpinBox(self.tab)
        self.spin_PrepNewRecipe.setGeometry(QtCore.QRect(80, 480, 71, 22))
        self.spin_PrepNewRecipe.setMinimum(0)
        self.spin_PrepNewRecipe.setMaximum(9999)
        self.spin_PrepNewRecipe.setObjectName("spin_PrepNewRecipe")
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(40, 90, 46, 13))
        self.label_12.setObjectName("label_12")
        self.line_NameNewRecipe = QtGui.QLineEdit(self.tab)
        self.line_NameNewRecipe.setGeometry(QtCore.QRect(80, 90, 261, 20))
        self.line_NameNewRecipe.setObjectName("line_NameNewRecipe")
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 61, 16))
        self.label_13.setObjectName("label_13")
        self.text_DescriptionNewRecipe = QtGui.QTextEdit(self.tab)
        self.text_DescriptionNewRecipe.setGeometry(QtCore.QRect(80, 150, 261, 221))
        self.text_DescriptionNewRecipe.setObjectName("text_DescriptionNewRecipe")
        self.spin_ServingsNewRecipe = QtGui.QSpinBox(self.tab)
        self.spin_ServingsNewRecipe.setGeometry(QtCore.QRect(80, 560, 71, 22))
        self.spin_ServingsNewRecipe.setMaximum(9999)
        self.spin_ServingsNewRecipe.setObjectName("spin_ServingsNewRecipe")
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(20, 560, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(430, 20, 91, 20))
        self.label_16.setObjectName("label_16")
        self.combo_IngredientTypeNewRecipe = QtGui.QComboBox(self.tab)
        self.combo_IngredientTypeNewRecipe.setGeometry(QtCore.QRect(530, 20, 231, 22))
        self.combo_IngredientTypeNewRecipe.setObjectName("combo_IngredientTypeNewRecipe")
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(370, 330, 51, 16))
        self.label_18.setObjectName("label_18")
        self.text_NewStep = QtGui.QTextEdit(self.tab)
        self.text_NewStep.setGeometry(QtCore.QRect(430, 320, 491, 51))
        self.text_NewStep.setObjectName("text_NewStep")
        self.button_AddNewStep = QtGui.QPushButton(self.tab)
        self.button_AddNewStep.setGeometry(QtCore.QRect(930, 350, 71, 21))
        self.button_AddNewStep.setObjectName("button_AddNewStep")
        self.table_AddedIngredients = QtGui.QTableWidget(self.tab)
        self.table_AddedIngredients.setGeometry(QtCore.QRect(430, 90, 441, 211))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_AddedIngredients.setFont(font)
        self.table_AddedIngredients.setObjectName("table_AddedIngredients")
        self.table_AddedIngredients.setColumnCount(3)
        self.table_AddedIngredients.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_AddedIngredients.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_AddedIngredients.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_AddedIngredients.setHorizontalHeaderItem(2, item)
        self.table_AddedIngredients.horizontalHeader().setMinimumSectionSize(0)
        self.table_AddedIngredients.horizontalHeader().setStretchLastSection(True)
        self.table_AddedIngredients.verticalHeader().setDefaultSectionSize(25)
        self.button_RemoveIngredient = QtGui.QPushButton(self.tab)
        self.button_RemoveIngredient.setGeometry(QtCore.QRect(880, 260, 101, 23))
        self.button_RemoveIngredient.setObjectName("button_RemoveIngredient")
        self.double_AmountNewRecipe = QtGui.QDoubleSpinBox(self.tab)
        self.double_AmountNewRecipe.setGeometry(QtCore.QRect(770, 20, 81, 22))
        self.double_AmountNewRecipe.setMaximum(9999.99)
        self.double_AmountNewRecipe.setSingleStep(0.5)
        self.double_AmountNewRecipe.setObjectName("double_AmountNewRecipe")
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(760, 50, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.button_DeleteStep = QtGui.QPushButton(self.tab)
        self.button_DeleteStep.setGeometry(QtCore.QRect(430, 580, 81, 23))
        self.button_DeleteStep.setObjectName("button_DeleteStep")
        self.table_CurrentSteps = QtGui.QTableWidget(self.tab)
        self.table_CurrentSteps.setGeometry(QtCore.QRect(430, 390, 641, 181))
        self.table_CurrentSteps.setObjectName("table_CurrentSteps")
        self.table_CurrentSteps.setColumnCount(1)
        self.table_CurrentSteps.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_CurrentSteps.setHorizontalHeaderItem(0, item)
        self.table_CurrentSteps.horizontalHeader().setDefaultSectionSize(30)
        self.table_CurrentSteps.horizontalHeader().setMinimumSectionSize(30)
        self.table_CurrentSteps.horizontalHeader().setStretchLastSection(True)
        self.table_CurrentSteps.verticalHeader().setDefaultSectionSize(25)
        self.table_CurrentSteps.verticalHeader().setStretchLastSection(False)
        self.button_Save = QtGui.QPushButton(self.tab)
        self.button_Save.setGeometry(QtCore.QRect(10, 10, 81, 23))
        self.button_Save.setObjectName("button_Save")
        self.label_SaveType = QtGui.QLabel(self.tab)
        self.label_SaveType.setGeometry(QtCore.QRect(100, 20, 91, 16))
        self.label_SaveType.setObjectName("label_SaveType")
        self.button_Discard = QtGui.QPushButton(self.tab)
        self.button_Discard.setGeometry(QtCore.QRect(10, 50, 81, 23))
        self.button_Discard.setObjectName("button_Discard")
        self.label_SaveType_2 = QtGui.QLabel(self.tab)
        self.label_SaveType_2.setGeometry(QtCore.QRect(100, 50, 261, 16))
        self.label_SaveType_2.setObjectName("label_SaveType_2")
        self.label_measureUnit = QtGui.QLabel(self.tab)
        self.label_measureUnit.setGeometry(QtCore.QRect(860, 20, 51, 20))
        self.label_measureUnit.setObjectName("label_measureUnit")
        self.spin_removeIngredient = QtGui.QSpinBox(self.tab)
        self.spin_removeIngredient.setGeometry(QtCore.QRect(990, 260, 61, 22))
        self.spin_removeIngredient.setMinimum(1)
        self.spin_removeIngredient.setMaximum(999)
        self.spin_removeIngredient.setObjectName("spin_removeIngredient")
        self.spin_removeStep = QtGui.QSpinBox(self.tab)
        self.spin_removeStep.setGeometry(QtCore.QRect(520, 580, 61, 22))
        self.spin_removeStep.setMinimum(1)
        self.spin_removeStep.setMaximum(999)
        self.spin_removeStep.setObjectName("spin_removeStep")
        self.label_uniqueName = QtGui.QLabel(self.tab)
        self.label_uniqueName.setGeometry(QtCore.QRect(80, 120, 281, 20))
        self.label_uniqueName.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_uniqueName.setText("")
        self.label_uniqueName.setObjectName("label_uniqueName")
        self.button_InsertStep = QtGui.QPushButton(self.tab)
        self.button_InsertStep.setGeometry(QtCore.QRect(930, 320, 71, 21))
        self.button_InsertStep.setObjectName("button_InsertStep")
        self.spin_InstertSpot = QtGui.QSpinBox(self.tab)
        self.spin_InstertSpot.setGeometry(QtCore.QRect(1010, 320, 51, 22))
        self.spin_InstertSpot.setMinimum(1)
        self.spin_InstertSpot.setMaximum(999)
        self.spin_InstertSpot.setObjectName("spin_InstertSpot")
        TabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(60, 10, 191, 20))
        self.label_17.setObjectName("label_17")
        self.combo_UnitNewIngredient = QtGui.QComboBox(self.tab_4)
        self.combo_UnitNewIngredient.setGeometry(QtCore.QRect(330, 40, 131, 22))
        self.combo_UnitNewIngredient.setObjectName("combo_UnitNewIngredient")
        self.line_IngredientAddToDB = QtGui.QLineEdit(self.tab_4)
        self.line_IngredientAddToDB.setGeometry(QtCore.QRect(50, 40, 241, 20))
        self.line_IngredientAddToDB.setObjectName("line_IngredientAddToDB")
        self.button_AddIngredientToDB = QtGui.QPushButton(self.tab_4)
        self.button_AddIngredientToDB.setGeometry(QtCore.QRect(470, 40, 31, 23))
        self.button_AddIngredientToDB.setObjectName("button_AddIngredientToDB")
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(300, 40, 31, 20))
        self.label_24.setObjectName("label_24")
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(10, 40, 51, 20))
        self.label_19.setObjectName("label_19")
        self.button_AddChefToDB = QtGui.QPushButton(self.tab_4)
        self.button_AddChefToDB.setGeometry(QtCore.QRect(310, 140, 31, 23))
        self.button_AddChefToDB.setObjectName("button_AddChefToDB")
        self.label_20 = QtGui.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(60, 110, 141, 20))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(10, 140, 51, 20))
        self.label_21.setObjectName("label_21")
        self.line_chefAddToDB = QtGui.QLineEdit(self.tab_4)
        self.line_chefAddToDB.setGeometry(QtCore.QRect(50, 140, 241, 20))
        self.line_chefAddToDB.setObjectName("line_chefAddToDB")
        self.button_AddApplianceToDB = QtGui.QPushButton(self.tab_4)
        self.button_AddApplianceToDB.setGeometry(QtCore.QRect(310, 270, 31, 23))
        self.button_AddApplianceToDB.setObjectName("button_AddApplianceToDB")
        self.line_applianceAddToDB = QtGui.QLineEdit(self.tab_4)
        self.line_applianceAddToDB.setGeometry(QtCore.QRect(50, 270, 241, 20))
        self.line_applianceAddToDB.setObjectName("line_applianceAddToDB")
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(60, 240, 141, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(10, 270, 51, 20))
        self.label_23.setObjectName("label_23")
        self.line_UnitAddToDB = QtGui.QLineEdit(self.tab_4)
        self.line_UnitAddToDB.setGeometry(QtCore.QRect(600, 40, 171, 20))
        self.line_UnitAddToDB.setObjectName("line_UnitAddToDB")
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(560, 40, 51, 20))
        self.label_26.setObjectName("label_26")
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(590, 10, 191, 16))
        self.label_7.setObjectName("label_7")
        self.button_AddIngredientToDB_2 = QtGui.QPushButton(self.tab_4)
        self.button_AddIngredientToDB_2.setGeometry(QtCore.QRect(790, 40, 31, 23))
        self.button_AddIngredientToDB_2.setObjectName("button_AddIngredientToDB_2")
        self.label_ingredientError = QtGui.QLabel(self.tab_4)
        self.label_ingredientError.setGeometry(QtCore.QRect(50, 70, 281, 20))
        self.label_ingredientError.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_ingredientError.setText("")
        self.label_ingredientError.setObjectName("label_ingredientError")
        self.label_chefError = QtGui.QLabel(self.tab_4)
        self.label_chefError.setGeometry(QtCore.QRect(50, 170, 281, 20))
        self.label_chefError.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_chefError.setText("")
        self.label_chefError.setObjectName("label_chefError")
        self.label_applianceError = QtGui.QLabel(self.tab_4)
        self.label_applianceError.setGeometry(QtCore.QRect(50, 300, 281, 20))
        self.label_applianceError.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_applianceError.setText("")
        self.label_applianceError.setObjectName("label_applianceError")
        self.label_unitError = QtGui.QLabel(self.tab_4)
        self.label_unitError.setGeometry(QtCore.QRect(560, 70, 281, 20))
        self.label_unitError.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_unitError.setText("")
        self.label_unitError.setObjectName("label_unitError")
        TabWidget.addTab(self.tab_4, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_Search, QtCore.SIGNAL("clicked()"), TabWidget.clickedSearch)
        QtCore.QObject.connect(self.button_DeleteRecipe, QtCore.SIGNAL("clicked()"), TabWidget.clickedDeleteRecipe)
        QtCore.QObject.connect(self.button_EditRecipe, QtCore.SIGNAL("clicked()"), TabWidget.clickedEditRecipe)
        QtCore.QObject.connect(self.button_ViewIngredients, QtCore.SIGNAL("clicked()"), TabWidget.clickedViewIngredients)
        QtCore.QObject.connect(self.button_ViewRecipes, QtCore.SIGNAL("clicked()"), TabWidget.clickedViewRecipes)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL("clicked()"), TabWidget.clickedAddIngredient)
        QtCore.QObject.connect(self.button_RemoveIngredient, QtCore.SIGNAL("clicked()"), TabWidget.clickedRemoveIngredient)
        QtCore.QObject.connect(self.button_AddNewStep, QtCore.SIGNAL("clicked()"), TabWidget.clickedAddStep)
        QtCore.QObject.connect(self.button_DeleteStep, QtCore.SIGNAL("clicked()"), TabWidget.clickedDeleteStep)
        QtCore.QObject.connect(self.button_Save, QtCore.SIGNAL("clicked()"), TabWidget.clickedSave)
        QtCore.QObject.connect(self.button_Discard, QtCore.SIGNAL("clicked()"), TabWidget.clickedDiscard)
        QtCore.QObject.connect(self.combo_IngredientTypeNewRecipe, QtCore.SIGNAL("currentIndexChanged(int)"), TabWidget.changedIngrediantAdd)
        QtCore.QObject.connect(self.button_InsertStep, QtCore.SIGNAL("clicked()"), TabWidget.clickedInsertStep)
        QtCore.QObject.connect(self.button_AddIngredientToDB, QtCore.SIGNAL("clicked()"), TabWidget.clickedIngredientAddToDatabase)
        QtCore.QObject.connect(self.button_AddChefToDB, QtCore.SIGNAL("clicked()"), TabWidget.clickedChefAddToDatabase)
        QtCore.QObject.connect(self.button_AddApplianceToDB, QtCore.SIGNAL("clicked()"), TabWidget.clickedApplianceAddToDatabase)
        QtCore.QObject.connect(self.button_AddIngredientToDB_2, QtCore.SIGNAL("clicked()"), TabWidget.clickedUnitAddToDatabase)
        QtCore.QObject.connect(self.button_addIngredientView, QtCore.SIGNAL("clicked()"), TabWidget.clickedAddIngredientView)
        QtCore.QObject.connect(self.combo_IngredientView, QtCore.SIGNAL("currentIndexChanged(int)"), TabWidget.changedIngredientView)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(QtGui.QApplication.translate("TabWidget", "TabWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Recipes.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("TabWidget", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Recipes.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("TabWidget", "Chef", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Recipes.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("TabWidget", "Appliance", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Recipes.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("TabWidget", "Prep Time", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Recipes.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("TabWidget", "Cook Time", None, QtGui.QApplication.UnicodeUTF8))
        self.table_Recipes.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("TabWidget", "Servings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TabWidget", "Chef:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TabWidget", "Appliance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TabWidget", "<  Prep Time <", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TabWidget", "<  Cook Time <", None, QtGui.QApplication.UnicodeUTF8))
        self.table_IngredientsFilter.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("TabWidget", "Ingredient Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TabWidget", "Recipes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TabWidget", "Ingredients", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Search.setText(QtGui.QApplication.translate("TabWidget", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.button_ViewIngredients.setText(QtGui.QApplication.translate("TabWidget", "View Ingredients ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_ViewRecipes.setText(QtGui.QApplication.translate("TabWidget", "View Recipes", None, QtGui.QApplication.UnicodeUTF8))
        self.button_EditRecipe.setText(QtGui.QApplication.translate("TabWidget", "Edit Recipe", None, QtGui.QApplication.UnicodeUTF8))
        self.button_DeleteRecipe.setText(QtGui.QApplication.translate("TabWidget", "Delete Recipe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("TabWidget", "<  Servings <", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("TabWidget", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_viewing.setText(QtGui.QApplication.translate("TabWidget", "Viewing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Output.setText(QtGui.QApplication.translate("TabWidget", "Recipes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_viewing_2.setText(QtGui.QApplication.translate("TabWidget", "Add Ingredient to list:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_addIngredientView.setText(QtGui.QApplication.translate("TabWidget", "Add Ingredient", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("TabWidget", "Label/Note:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_measureUnitView.setText(QtGui.QApplication.translate("TabWidget", "Unit  NA", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("TabWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TabWidget", "Chef:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TabWidget", "Cook Time: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TabWidget", "Appliance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TabWidget", "Prep Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("TabWidget", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("TabWidget", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("TabWidget", "Servings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("TabWidget", "Ingredient Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("TabWidget", "New Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_AddNewStep.setText(QtGui.QApplication.translate("TabWidget", "Add Step", None, QtGui.QApplication.UnicodeUTF8))
        self.table_AddedIngredients.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("TabWidget", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.table_AddedIngredients.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("TabWidget", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.table_AddedIngredients.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("TabWidget", "Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.button_RemoveIngredient.setText(QtGui.QApplication.translate("TabWidget", "Remove Ingredient", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("TabWidget", "Add Ingredient", None, QtGui.QApplication.UnicodeUTF8))
        self.button_DeleteStep.setText(QtGui.QApplication.translate("TabWidget", "Delete Step", None, QtGui.QApplication.UnicodeUTF8))
        self.table_CurrentSteps.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("TabWidget", "Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Save.setText(QtGui.QApplication.translate("TabWidget", "SAVE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SaveType.setText(QtGui.QApplication.translate("TabWidget", "As a new Recipe", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Discard.setText(QtGui.QApplication.translate("TabWidget", "Discard", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SaveType_2.setText(QtGui.QApplication.translate("TabWidget", "(No changes to recipe book, start a fresh recipe)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_measureUnit.setText(QtGui.QApplication.translate("TabWidget", "Unit  NA", None, QtGui.QApplication.UnicodeUTF8))
        self.button_InsertStep.setText(QtGui.QApplication.translate("TabWidget", "Insert After", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), QtGui.QApplication.translate("TabWidget", "Create/Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("TabWidget", "Add Ingredient Type To Database", None, QtGui.QApplication.UnicodeUTF8))
        self.button_AddIngredientToDB.setText(QtGui.QApplication.translate("TabWidget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("TabWidget", "Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("TabWidget", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_AddChefToDB.setText(QtGui.QApplication.translate("TabWidget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("TabWidget", "Add Chef To Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("TabWidget", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_AddApplianceToDB.setText(QtGui.QApplication.translate("TabWidget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("TabWidget", "Add Appliance To Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("TabWidget", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("TabWidget", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TabWidget", "Add Measuring Unit To Database", None, QtGui.QApplication.UnicodeUTF8))
        self.button_AddIngredientToDB_2.setText(QtGui.QApplication.translate("TabWidget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("TabWidget", "Config", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TabWidget = QtGui.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())

